### ISSUE TITLE
Rejects `|` in username.

### ISSUE THREAD

**Issue by AshtonHarding** [mariari/vomitchan#1]
> <@kashire|t420> \*vomits\*
> \*cricket noises\*

**Comment by mariari** [comment]
> > <@kashire|t420> *vomits*
> > *cricket noises*

[The latest commit fixes this!](https://github.com/mariari/vomitchan/commit/02d9da4e93e2dac81c2886b7e7eef780b5ff62f3)

Thanks for the report

**\*cheek pinch\***
